### ISSUE TITLE
Unable to build on Espressif SDK 0.9.5

### ISSUE THREAD

**Issue by geekscape** [cnlohr/dumbcraft8266#1]
hi Charles, really nice piece of work.  I was able to flash/run your pre-built image ... and now keen to hack on the code.  However, I've not been able to do that successfully.

The main problem being that I'm not sure which LD SCRIPT to use (not obvious from looking at your Makefile).

I've tried using a stock-standard Makefile (from SDK 0.9.5 examples) and LD SCRIPT and ...
1) Using "user/user_main.c" the link fails with "ld: build/app.out section `.text' will not fit in region`iram1_0_seg'"
2) Using "user/user_main.c.minimal.txt compiles, links and can be flashed into the ESP8266, but doesn't work

Do you have any advice on how to compile / link and run this code on ESP8266 SDK 0.9.5, please ?

**Comment by cnlohr** [comment]
Indeed you are correct, the iram is out of room.  Try adding ICACHE_FLASH_ATTR to some of the larger functions.  That should free up your iram.

**Comment by geekscape** [comment]
I will try that.  I was hoping that since you'd successfully build the image previously ... that you wouldn't mind filling in the gaps regarding that build.  It would be a great outcome if DumbCraft8266 ran on the latest Espressif SDK.

**Comment by cnlohr** [comment]
I will put this on my list, but at the moment, both my jobs are running me pretty hard, so I have very little free time.  There is a possibility it'll happen today, though.

**Comment by geekscape** [comment]
Ah, in that case ... don't want to make things more stressful.  My interest is to play around with a fun ESP8266 hack ... and not to eat into your valuable free time.  Whenever is fine ... thanks !

**Comment by cnlohr** [comment]
This project has been superseded and now works in esp82xx. https://github.com/cnlohr/avrcraft  check out the esp8266 folder.
