### ISSUE TITLE
cannot find eagle.rom.addr.v6.ld

### ISSUE THREAD

**Issue by ghost** [cnlohr/dumbcraft8266#2]
xtensa gcc can't find eagle.rom.addr.v6.ld even when it's path is correct.
This is the gcc execution line:
source@megumi:~/git/dumbcraft8266$ make
/storage/mirror/home/source/esp8266/xtensa-toolchain-build/build-lx106/root/bin/xtensa-lx106-elf-gcc driver/uart.c user/dumbcraft.c user/dumbutils.c user/user_main.c user/dumbgame.c user/mystuff.c user/util10.c -mlongcalls -I/storage/mirror/home/source/esp8266/esp_iot_sdk_v1.3.0/include -Imyclib -Iinclude -Iuser -Os -I/storage/mirror/home/source/esp8266/esp_iot_sdk_v1.3.0/lib_from_xt/lx106/xtensa-elf/include/ -flto /storage/mirror/home/source/esp8266/esp_iot_sdk_v1.3.0/lib/libmain.a /storage/mirror/home/source/esp8266/esp_iot_sdk_v1.3.0/lib/liblwip.a /storage/mirror/home/source/esp8266/esp_iot_sdk_v1.3.0/lib/libphy.a /storage/mirror/home/source/esp8266/esp_iot_sdk_v1.3.0/lib/libssl.a /storage/mirror/home/source/esp8266/esp_iot_sdk_v1.3.0/lib/libupgrade.a /storage/mirror/home/source/esp8266/esp_iot_sdk_v1.3.0/lib/libupgrade_ssl.a /storage/mirror/home/source/esp8266/esp_iot_sdk_v1.3.0/lib/libnet80211.a /storage/mirror/home/source/esp8266/esp_iot_sdk_v1.3.0/lib/libwpa.a /storage/mirror/home/source/esp8266/esp_iot_sdk_v1.3.0/lib/libnet80211.a -L/storage/mirror/home/source/esp8266/esp_iot_sdk_v1.3.0/lib_from_xt/lx106/xtensa-elf/arch/lib -L/storage/mirror/home/source/esp8266/esp_iot_sdk_v1.3.0/lib_from_xt/lx106/xtensa-elf/lib -T/storage/mirror/home/source/esp8266/esp_iot_sdk_v1.3.0/ld/eagle.app.v6.ld -B/storage/mirror/home/source/esp8266/esp_iot_sdk_v1.3.0/lib_from_xt/lx106/xtensa-elf/lib -B/storage/mirror/home/source/esp8266/esp_iot_sdk_v1.3.0/lib_from_xt/lx106/xtensa-elf/lib/../arch/lib -o image.elf

Ends with this error message:
/storage/mirror/home/source/esp8266/xtensa-toolchain-build/build-lx106/root/lib/gcc/xtensa-lx106-elf/4.8.2/../../../../xtensa-lx106-elf/bin/ld: cannot open linker script file ../ld/eagle.rom.addr.v6.ld: No such file or directory

From the Makefile: 
-T$(SDK)/ld/eagle.app.v6.ld
and $(SDK):
SDK:=$(HOME)/esp8266/esp_iot_sdk_v1.3.0

It points to the right place as seen in the gcc execution, but I don't know enough about how linkage works to know why it's looking for the file in the wrong place..
I've seen this sort of problem before, but I cannot remember or find good enough info about how to repair this, sorry.

**Comment by cnlohr** [comment]
Do you have a copy of the esp8266 esp_iot_sdk_1.3.0 in your ~/esp8266 folder?

**Comment by ghost** [comment]
yes

**Comment by cnlohr** [comment]
Second question: Did you set your home folder to be a relative path?  You can't do that.  The fact it's looking in ../ is concerning.  I don't really understand why relative paths aren't permitted, but I have run into a similar problem.

**Comment by ghost** [comment]
Sorry, I'm not quite sure what you mean by relative path, could you explain ?
These are the relevant lines in the Makefile:

ESPTOOL_PY:=$(HOME)/esp8266/esptool/esptool.py
FW_TOOL:=$(HOME)/esp8266/esptool/other/esptool/esptool
SDK:=$(HOME)/esp8266/esp_iot_sdk_v1.3.0
XTLIB:=$(SDK)/lib_from_xt/lx106/xtensa-elf/lib
FOLDERPREFIX=$(HOME)/esp8266/xtensa-toolchain-build/build-lx106/root/bin
PREFIX:=$(FOLDERPREFIX)/xtensa-lx106-elf-
CC:=$(PREFIX)gcc

**Comment by con-f-use** [comment]
`HOME` is a built-in variable in gnu make and usually an absolute path.. I think he was asking if you set `$(HOME)` to something like `../../source83`. This Makefile should return something that starts with a dash `/` 

```
.PHONY: all

all:
    @echo "$(HOME); user $(USER)"
```

If it doesn't, you should set it to something like `/home/YOUR-USER-NAME`. 

---

HOWEVER, I'm very sure that isn't the issue, because I have the same problem, and my Makefile looks like this:

```
ESP_ROOT:=/home/confus/usr/build/esp-open-sdk
GCC_FOLDER:=$(ESP_ROOT)/xtensa-lx106-elf
ESPTOOL_PY:=$(ESP_ROOT)/esptool/esptool.py
FW_TOOL=$(ESP_ROOT)/esptool
SDK:=$(ESP_ROOT)/sdk
```

Most baffling is, I get another error if I replace `/home/confus` by simply `~`.
Did you solve your problem yet? Does anyone have other suggestions?

**Comment by cnlohr** [comment]
Woah, this project is a blast from the past.  I try to keep my makefile in esp8266ws2812i2s up-to-date.  Should be able to compare the two.

I would be shocked if this project worked with newer SDKs though since it was way back when, before I knew what I was doing at all.

**Comment by mabushey** [comment]
```
ESP_ROOT:=/home/confus/usr/build/esp-open-sdk
GCC_FOLDER:=$(ESP_ROOT)/xtensa-lx106-elf
ESPTOOL_PY:=$(ESP_ROOT)/esptool/esptool.py
FW_TOOL=$(ESP_ROOT)/esptool
SDK:=$(ESP_ROOT)/sdk
```

Shouldn't the FW_TOOL line be `FW_TOOL:=$(ESP_ROOT)/esptool`? (It's missing the `:`)

**Comment by con-f-use** [comment]
Shouldn't make a difference.

**Comment by cnlohr** [comment]
@con-f-use ... are we actually going to make the minecraft server work again?  And bring it into the new millennium with esp82xx???  If so that would be so much cool!  I have some awesome ideas.  I just haven't had the time to update it.

**Comment by cnlohr** [comment]
This now works in esp82xx, please check it out here https://github.com/cnlohr/avrcraft in the esp8266 folder.
